import = [
    "~/.config/alacritty/themes/tilwe.toml",
]

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
opacity = 0.9

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 10

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "W", mods = "Control", action = "Quit" },
]
