import = [
    "~/.config/alacritty/themes/tilwe.toml",
]

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[font]
normal = { family = "JetBrains Mono", style = "Medium" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "MediumItalic" }
bold_italic = { family = "JetBrains Mono", style = "BoldItalic" }
size = 10
