[colors]
[colors.primary]
background = "#14161a"
foreground = "#d8d8d8"
[colors.normal]
black = "#000000"
red = "#c91b00"
green = "#00c200"
yellow = "#fbff00"
blue = "#2e74ff"
magenta = "#e000ff"
cyan = "#00c5c7"
white = "#d8d8d8"
[colors.bright]
black = "#676767"
red = "#ff6d67"
green = "#46f54f"
yellow = "#f3f054"
blue = "#4086f4"
magenta = "#ff76ff"
cyan = "#5ffdff"
white = "#ffffff"
