# sensible options
set -g mouse on

# window numbering
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# split panes
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# kill panes
bind-key x kill-pane
bind-key & kill-window

# zoom / maximize pane
bind -r m resize-pane -Z

# switch sessions
unbind Enter
bind Enter choose-session

# status line
set-option -g status-style bg=default
set -g status-fg white
set -g status-left-length 20
set -g status-left "#S"
set -g status-right ""
set -g status-justify absolute-centre

# pane-border
set -g pane-border-indicators off
set -g pane-border-style fg=black
set -g pane-active-border-style fg=black

# copy mode
# move character    | j k h l
# move line         | Ctrl+Y Ctrl+E
# move whole screen | Ctrl+B Ctrl+F
# search            | /
# start selection   | Space
# copy selection    | Enter
# clear selection   | Escape
# exit copy mode    | q
set -g mode-keys vi
set -g status-keys vi

# source config
bind r source-file ~/.config/tmux/tmux.conf

# plugins
bind C-l send-keys 'C-l'    # prefix C-l to clear screen
