# sensible options
set -g mouse on

# window numbering
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# split panes
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# zoom / maximize pane
bind -r m resize-pane -Z

# status line
set-option -g status-style bg=default
set -g status-fg white

# tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
bind C-l send-keys 'C-l'    # prefix C-l to clear screen
set -g @plugin 'tmux-plugins/tmux-resurrect'    # keep sessions alive
set -g @plugin 'tmux-plugins/tmux-continuum'    # auto save sessions

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
