# sensible options
set -g mouse on

# window numbering
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# split panes
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# kill panes
bind-key x kill-pane
bind-key & kill-window

# zoom / maximize pane
bind -r m resize-pane -Z

# switch sessions
unbind Enter
bind Enter choose-session

# status line
set-option -g status-style bg=default
set -g status-fg white
set -g status-left-length 20
set -g status-right ""

# copy mode
# move character    | j k h l
# move line         | Ctrl+Y Ctrl+E
# move whole screen | Ctrl+B Ctrl+F
# search            | /
# start selection   | Space
# copy selection    | Enter
# clear selection   | Escape
# exit copy mode    | q
set -g mode-keys vi
set -g status-keys vi

# source config
bind r source-file ~/.config/tmux/tmux.conf

# tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
bind C-l send-keys 'C-l'    # prefix C-l to clear screen
set -g @plugin 'tmux-plugins/tmux-resurrect'    # keep sessions alive
set -g @plugin 'tmux-plugins/tmux-continuum'    # auto save sessions

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
